// Static fallback menu for complete offline functionality
const FALLBACK_IMAGE =
  "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAwIiBoZWlnaHQ9IjMwMCIgdmlld0JveD0iMCAwIDQwMCAzMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSI0MDAiIGhlaWdodD0iMzAwIiBmaWxsPSIjRjNGNEY2Ii8+CjxyZWN0IHg9IjE2MCIgeT0iMTEwIiB3aWR0aD0iODAiIGhlaWdodD0iODAiIGZpbGw9IiM5Q0E0QUYiLz4KPHN2ZyB4PSIxODAiIHk9IjEzMCIgd2lkdGg9IjQwIiBoZWlnaHQ9IjQwIiBmaWxsPSIjNkI3MjgwIj4KICA8cGF0aCBkPSJNMjAgNmE4IDggMCAwIDEgOCA4djhoMS41YTEuNSAxLjUgMCAwIDEgMCAzSDE5djhoMS41YTEuNSAxLjUgMCAwIDEgMCAzSDEwLjVhMS41IDEuNSAwIDAgMSAwLTNIMTJWMjJoLTEuNWExLjUgMS41IDAgMCAxIDAtM0gxMnYtOGE4IDggMCAwIDEgOC04em0wIDJhNiA2IDAgMCAwLTYgNnY4aDEydi04YTYgNiAwIDAgMC02LTZ6bS0yIDEwYzAtMS4xMDUuODk1LTIgMi0yczIgLjg5NSAyIDItLjg5NSAyLTIgMi0yLS44OTUtMi0yeiIvPgo8L3N2Zz4KPC9zdmc+";

export const FALLBACK_MENU = [
  {
    menu_id: 1,
    dish_name: "Classic Beef Burger",
    price: 299,
    image_url: FALLBACK_IMAGE,
    description:
      "Juicy beef patty with fresh lettuce, tomatoes, and our special sauce",
    category: "Burgers",
    stock_status: "available",
  },
  {
    menu_id: 2,
    dish_name: "Chicken Wings (6pcs)",
    price: 249,
    image_url: FALLBACK_IMAGE,
    description: "Crispy chicken wings tossed in your choice of sauce",
    category: "Appetizers",
    stock_status: "available",
  },
  {
    menu_id: 3,
    dish_name: "Margherita Pizza",
    price: 399,
    image_url: FALLBACK_IMAGE,
    description: "Classic pizza with fresh mozzarella, tomatoes, and basil",
    category: "Pizza",
    stock_status: "available",
  },
  {
    menu_id: 4,
    dish_name: "Caesar Salad",
    price: 199,
    image_url: FALLBACK_IMAGE,
    description:
      "Fresh romaine lettuce with parmesan cheese and caesar dressing",
    category: "Salads",
    stock_status: "available",
  },
  {
    menu_id: 5,
    dish_name: "Grilled Chicken",
    price: 349,
    image_url: FALLBACK_IMAGE,
    description: "Tender grilled chicken breast with herbs and spices",
    category: "Main Course",
    stock_status: "available",
  },
  {
    menu_id: 6,
    dish_name: "Fish and Chips",
    price: 329,
    image_url: FALLBACK_IMAGE,
    description: "Crispy battered fish with golden fries and tartar sauce",
    category: "Main Course",
    stock_status: "available",
  },
  {
    menu_id: 7,
    dish_name: "Chocolate Cake",
    price: 149,
    image_url: FALLBACK_IMAGE,
    description: "Rich chocolate cake with smooth chocolate frosting",
    category: "Desserts",
    stock_status: "available",
  },
  {
    menu_id: 8,
    dish_name: "Fresh Orange Juice",
    price: 89,
    image_url: FALLBACK_IMAGE,
    description: "Freshly squeezed orange juice served chilled",
    category: "Beverages",
    stock_status: "available",
  },
  {
    menu_id: 9,
    dish_name: "Spaghetti Carbonara",
    price: 279,
    image_url: FALLBACK_IMAGE,
    description: "Creamy pasta with bacon, eggs, and parmesan cheese",
    category: "Pasta",
    stock_status: "available",
  },
  {
    menu_id: 10,
    dish_name: "Iced Coffee",
    price: 99,
    image_url: FALLBACK_IMAGE,
    description: "Cold brew coffee served with ice and cream",
    category: "Beverages",
    stock_status: "available",
  },
];
